class Form:
    txt_f_name = "customer_firstname"
    txt_l_name = "customer_lastname"
    txt_password = "passwd"
    ddl_days = "days"
    ddl_months = "months"
    ddl_years = "years"
    txt_company = "company"
    txt_address_1 = "address1"
    txt_city = "city"
    ddl_state = "id_state"
    txt_postcode = "postcode"
    ddl_country = "id_country"
    txt_mobile = "phone_mobile"
    btn_register = "//span[contains(.,'Register')]"
